version: "3.9"

services:
  config-server:
    image: mojtaba2422/ecommerce-config-server:latest
    container_name: ecommerce-config-server
    ports:
      - "8888:8888"
    environment:
      - EUREKA_SERVER_URL=http://ecommerce-eureka-server:9999/eureka
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge
    external: true
